steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build"
    args:
      [
        "build",
        "-t",
        "gcr.io/rama-lab/github.com/ramadlana/rama-reactjs-starterkit:$SHORT_SHA",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: "push"
    waitFor: ["build"]
    args:
      [
        "push",
        "gcr.io/rama-lab/github.com/ramadlana/rama-reactjs-starterkit:$SHORT_SHA",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy"
    waitFor: ["push"]
    args:
      [
        "run",
        "deploy",
        "reactstarterkit",
        "--image=gcr.io/rama-lab/github.com/ramadlana/rama-reactjs-starterkit:$SHORT_SHA",
        "--allow-unauthenticated",
        "--region=asia-southeast2",
        "--max-instances=1",
        "--project=rama-lab",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    id: "update-traffic"
    waitFor: ["deploy"]
    args:
      [
        "run",
        "services",
        "update-traffic",
        "reactstarterkit",
        "--to-latest",
        "--region=asia-southeast2",
      ]
